apiVersion: apps/v1
kind: Deployment
metadata:
  name: peyk-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peyk-deployment
  template:
    metadata:
      labels:
        app: peyk-deployment
    spec:
      volumes:
        - name: peyk-volume
          hostPath:
            path: /app/project_peyk
      containers:
        - name: peyk-deployment
          image: peyk:v1
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: beap-volume
              mountPath: /app/project_peyk
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APP_IP
              valueFrom:
                configMapKeyRef:
                  name: peyk-configmap
                  key: app.ip
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: peyk-configmap
                  key: app.port
