apiVersion: v1
kind: Service
metadata:
  name: peyk-service
spec:
  selector:
    app: peyk-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30000
    